services:
  db: 
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: myuser
      MYSQL_DATABASE: crud_operations
    ports:
      - 3306:3306

  backend:
    container_name: backend
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    
  frontend:
    container_name: frontend
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  
